name: Coverage

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ development ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      TZ: "/usr/share/zoneinfo/your/location"
    steps:
      - uses: actions/checkout@v4
      - name: Cache .cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ./target
          key: ${{ runner.os }}-coverage-cargo-${{ hashFiles('Cargo.toml') }}
          restore-keys: ${{ runner.os }}-coverage-cargo
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo-tarpaulin
        run: cargo install --locked cargo-tarpaulin
      - name: Run cargo-tarpaulin
        run: cargo tarpaulin --all-features --run-types Tests --run-types Doctests --out Lcov --fail-under 44 -- --test-threads 1
      - name: Upload to codecov.io
        if: always()
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
