name: Lint checks

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ development ]


jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      TZ: "/usr/share/zoneinfo/your/location"
    steps:
      - uses: actions/checkout@v4
      - name: Cache .cargo and target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ./target
          key: ${{ runner.os }}-lint-cargo-${{ hashFiles('Cargo.toml') }}
          restore-keys: ${{ runner.os }}-lint-cargo
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-features -- -Drust-2018-idioms -Dwarnings
